# TF-IDF with KNN

In [1]:
# Import library 
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Mengambil data dari csv
# df = pd.read_csv('tf-idf_halodocnew_1.csv')
df = pd.read_csv('df_new_query (1).csv')

print(df.shape)

df.head()

(9979, 20)

,url,title,title_count,content,content_count,title_tokens,content_tokens,title_tokens_stopwords,title_tokens_stopwords_count,content_tokens_stopwords,content_tokens_stopwords_count,title_tokens_stopwords_stemmed,title_tokens_stopwords_stemmed_count,content_tokens_stopwords_stemmed,content_tokens_stopwords_stemmed_count,document_id,new_query,new_query_tokens,new_query_tokens_stopwords,new_query_tokens_stopwords_stemmed
0,https://www.halodoc.com/ibu-perhatikan-5-hal-i...,"ibu, perhatikan 5 hal ini saat memilih car se...",11,"bagi orang tua yang memiliki kendaraan, memili...",575,"['ibu', ',', 'perhatikan', '5', 'hal', 'ini', ...","['bagi', 'orang', 'tua', 'yang', 'memiliki', '...","[',', 'perhatikan', '5', 'memilih', 'car', 'se...",7,"['orang', 'tua', 'memiliki', 'kendaraan', ',',...",339,"['', 'perhati', '5', 'pilih', 'car', 'seat', '...",7,"['orang', 'tua', 'milik', 'kendara', '', 'memi...",339,0,cara memilih seat bayi baru lahir,"['cara', 'memilih', 'seat', 'bayi', 'baru', 'l...","['memilih', 'seat', 'bayi', 'lahir']","['pilih', 'seat', 'bayi', 'lahir']"
1,https://www.halodoc.com/catat-ini-6-tips-menyi...,"catat, ini 6 tips menyimpan beras agar tidak ...",10,sebagai makanan pokok beras harus disimpan den...,617,"['catat', ',', 'ini', '6', 'tips', 'menyimpan'...","['sebagai', 'makanan', 'pokok', 'beras', 'haru...","['catat', ',', '6', 'tips', 'menyimpan', 'bera...",7,"['makanan', 'pokok', 'beras', 'disimpan', 'kua...",347,"['catat', '', '6', 'tips', 'simpan', 'beras', ...",7,"['makan', 'pokok', 'beras', 'simpan', 'kualita...",347,1,NaN,[],[],[]
2,https://www.halodoc.com/waspada-ini-6-bahaya-a...,"waspada, ini 6 bahaya asap rokok bagi kesehat...",10,merokok tidak hanya berbahaya untuk dirimu sen...,708,"['waspada', ',', 'ini', '6', 'bahaya', 'asap',...","['merokok', 'tidak', 'hanya', 'berbahaya', 'un...","['waspada', ',', '6', 'bahaya', 'asap', 'rokok...",8,"['merokok', 'berbahaya', 'dirimu', 'orang-oran...",438,"['waspada', '', '6', 'bahaya', 'asap', 'rokok'...",8,"['rokok', 'bahaya', 'diri', 'orang', 'sekitar'...",438,2,NaN,[],[],[]
3,https://www.halodoc.com/sering-terkena-polusi-...,"sering terkena polusi, ketahui berbagi cara b...",9,"sehari-hari, manusia terpapar polusi dalam jum...",569,"['sering', 'terkena', 'polusi', ',', 'ketahui'...","['sehari-hari', ',', 'manusia', 'terpapar', 'p...","['terkena', 'polusi', ',', 'ketahui', 'berbagi...",7,"['sehari-hari', ',', 'manusia', 'terpapar', 'p...",342,"['kena', 'polusi', '', 'tahu', 'bagi', 'sih', ...",7,"['hari', '', 'manusia', 'papar', 'polusi', 'as...",342,3,NaN,[],[],[]
4,https://www.halodoc.com/ini-risiko-dan-manfaat...,ini risiko dan manfaat implan payudara yang p...,9,implan payudara adalah prosedur bedah kosmetik...,613,"['ini', 'risiko', 'dan', 'manfaat', 'implan', ...","['implan', 'payudara', 'adalah', 'prosedur', '...","['risiko', 'manfaat', 'implan', 'payudara']",4,"['implan', 'payudara', 'prosedur', 'bedah', 'k...",362,"['risiko', 'manfaat', 'implan', 'payudara']",4,"['implan', 'payudara', 'prosedur', 'bedah', 'k...",362,4,NaN,[],[],[]

In [2]:
# Read scraping/halodocnew_1.csv
df_halodocnew_1 = pd.read_csv('scraping/halodocnew_1.csv')
print(len(df_halodocnew_1))

# Ubah kolom "title" dan "content" di df menjadi df_halodocnew_1 (mengembali ke bentuk semula/cased)
df['title'] = df_halodocnew_1['title']
df['content'] = df_halodocnew_1['content']
df.head(1)

9979

,url,title,title_count,content,content_count,title_tokens,content_tokens,title_tokens_stopwords,title_tokens_stopwords_count,content_tokens_stopwords,content_tokens_stopwords_count,title_tokens_stopwords_stemmed,title_tokens_stopwords_stemmed_count,content_tokens_stopwords_stemmed,content_tokens_stopwords_stemmed_count,document_id,new_query,new_query_tokens,new_query_tokens_stopwords,new_query_tokens_stopwords_stemmed
0,https://www.halodoc.com/ibu-perhatikan-5-hal-i...,"Ibu, Perhatikan 5 Hal Ini saat Memilih Car Se...",11,"Bagi orang tua yang memiliki kendaraan, memili...",575,"['ibu', ',', 'perhatikan', '5', 'hal', 'ini', ...","['bagi', 'orang', 'tua', 'yang', 'memiliki', '...","[',', 'perhatikan', '5', 'memilih', 'car', 'se...",7,"['orang', 'tua', 'memiliki', 'kendaraan', ',',...",339,"['', 'perhati', '5', 'pilih', 'car', 'seat', '...",7,"['orang', 'tua', 'milik', 'kendara', '', 'memi...",339,0,cara memilih seat bayi baru lahir,"['cara', 'memilih', 'seat', 'bayi', 'baru', 'l...","['memilih', 'seat', 'bayi', 'lahir']","['pilih', 'seat', 'bayi', 'lahir']"

In [3]:
# Melakukan konversi data yang sebelumnya bertipe string agar bisa diolah pada tahap selanjutnya

import ast

df['title_tokens'] = df['title_tokens'].apply(ast.literal_eval)
df['content_tokens'] = df['content_tokens'].apply(ast.literal_eval)
df['title_tokens_stopwords'] = df['title_tokens_stopwords'].apply(ast.literal_eval)
df['content_tokens_stopwords'] = df['content_tokens_stopwords'].apply(ast.literal_eval)
df['content_tokens_stopwords_stemmed'] = df['content_tokens_stopwords_stemmed'].apply(ast.literal_eval)
df['title_tokens_stopwords_stemmed'] = df['title_tokens_stopwords_stemmed'].apply(ast.literal_eval)

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

# Mendefiniskan konfigurasi untuk Nearest Neighbors
retriever_configs = {
    'n_neighbors': 1,  # Jumlah tetangga/dokumen terdekat yang akan dicari
    'metric': 'cosine'  # Fungsi similarity yang akan digunakan
}

# Mendefinisikan pipeline untuk sistem Information Retrieval
# menggunakan TF-IDF dan Nearest Neighbors (dengan metrik cosine similarity)
embedding = TfidfVectorizer()
retriever = NearestNeighbors(**retriever_configs)

In [5]:
# Membuat pipeline untuk knn dengan nilai n tetangga = 3 dan 10
retriever_3_configs = {
    'n_neighbors': 3,  # Jumlah tetangga/dokumen terdekat yang akan dicari
    'metric': 'cosine'  # Fungsi similarity yang akan digunakan
}
retriever_3 = NearestNeighbors(**retriever_3_configs)

retriever_9_configs = {
    'n_neighbors': 9,  # Jumlah tetangga/dokumen terdekat yang akan dicari
    'metric': 'cosine'  # Fungsi similarity yang akan digunakan
}
retriever_9 = NearestNeighbors(**retriever_9_configs)

In [6]:
# Fungsi untuk melakukan transformasi teks menjadi vektor
def transform_text(vectorizer, text):
    print('Text:', text)
    vector = vectorizer.transform([text])
    vector = vectorizer.inverse_transform(vector)
    print('Vect:', vector)

# Melakukan transformasi teks menjadi vektor dengan fungsi transform_text
# transform_text(embedding, question)

In [7]:
def top_accuracy(y_true, y_pred) -> float:
    right, count = 0, 0
    for i, y_t in enumerate(y_true):
        count += 1
        if y_t in y_pred[i]:
            right += 1
    return right / count if count > 0 else 0

----

In [8]:
# read tf-idf_train.csv 
df_json = pd.read_csv('tf-idf_train.csv')
df_json.head(1)

,id,text,label,text_word_count,label_word_count,text_lower,label_lower,text_tokens,label_tokens,text_tokens_stopwords,label_tokens_stopwords,text_tokens_stopwords_stemmed,label_tokens_stopwords_stemmed
0,1501893029-lula-kamal-dokter-ryan-thamrin-saki...,"Dokter Ryan Thamrin , yang terkenal lewat aca...",Dokter Lula Kamal yang merupakan selebriti sek...,330,58,"dokter ryan thamrin , yang terkenal lewat aca...",dokter lula kamal yang merupakan selebriti sek...,"['dokter', 'ryan', 'thamrin', ',', 'yang', 'te...","['dokter', 'lula', 'kamal', 'yang', 'merupakan...","['dokter', 'ryan', 'thamrin', ',', 'terkenal',...","['dokter', 'lula', 'kamal', 'selebriti', 'reka...","['dokter', 'ryan', 'thamrin', '', 'kenal', 'ac...","['dokter', 'lula', 'kamal', 'selebriti', 'reka..."

In [9]:
# ast literal on text_tokens_stopwords_stemmed and label_tokens_stopwords_stemmed
df_json['text_tokens_stopwords_stemmed'] = df_json['text_tokens_stopwords_stemmed'].apply(ast.literal_eval)
df_json['label_tokens_stopwords_stemmed'] = df_json['label_tokens_stopwords_stemmed'].apply(ast.literal_eval)
df_json.head(1)

,id,text,label,text_word_count,label_word_count,text_lower,label_lower,text_tokens,label_tokens,text_tokens_stopwords,label_tokens_stopwords,text_tokens_stopwords_stemmed,label_tokens_stopwords_stemmed
0,1501893029-lula-kamal-dokter-ryan-thamrin-saki...,"Dokter Ryan Thamrin , yang terkenal lewat aca...",Dokter Lula Kamal yang merupakan selebriti sek...,330,58,"dokter ryan thamrin , yang terkenal lewat aca...",dokter lula kamal yang merupakan selebriti sek...,"['dokter', 'ryan', 'thamrin', ',', 'yang', 'te...","['dokter', 'lula', 'kamal', 'yang', 'merupakan...","['dokter', 'ryan', 'thamrin', ',', 'terkenal',...","['dokter', 'lula', 'kamal', 'selebriti', 'reka...","[dokter, ryan, thamrin, , kenal, acara, dokter...","[dokter, lula, kamal, selebriti, rekan, kerja,..."

In [10]:
# change df_json columns name
#  - text -> content
#  - label -> title
#  - text_tokens_stopwords_stemmed -> content_tokens_stopwords_stemmed
#  - label_tokens_stopwords_stemmed -> title_tokens_stopwords_stemmed

df_json = df_json.rename(columns={'text': 'content', 'label': 'title', 'text_tokens_stopwords_stemmed': 'content_tokens_stopwords_stemmed', 'label_tokens_stopwords_stemmed': 'title_tokens_stopwords_stemmed'})
df_json.head(1)

,id,content,title,text_word_count,label_word_count,text_lower,label_lower,text_tokens,label_tokens,text_tokens_stopwords,label_tokens_stopwords,content_tokens_stopwords_stemmed,title_tokens_stopwords_stemmed
0,1501893029-lula-kamal-dokter-ryan-thamrin-saki...,"Dokter Ryan Thamrin , yang terkenal lewat aca...",Dokter Lula Kamal yang merupakan selebriti sek...,330,58,"dokter ryan thamrin , yang terkenal lewat aca...",dokter lula kamal yang merupakan selebriti sek...,"['dokter', 'ryan', 'thamrin', ',', 'yang', 'te...","['dokter', 'lula', 'kamal', 'yang', 'merupakan...","['dokter', 'ryan', 'thamrin', ',', 'terkenal',...","['dokter', 'lula', 'kamal', 'selebriti', 'reka...","[dokter, ryan, thamrin, , kenal, acara, dokter...","[dokter, lula, kamal, selebriti, rekan, kerja,..."

In [12]:
# combine df_json and df to df_combined
#  - df == df_json (was)
# - 'content' = 'text'
# - 'title' = 'label'
# - 'content_tokens_stopwords_stemmed' = 'text_tokens_stopwords_stemmed'
# - 'title_tokens_stopwords_stemmed' = 'label_tokens_stopwords_stemmed'

columns = ['content', 'title', 'content_tokens_stopwords_stemmed', 'title_tokens_stopwords_stemmed']

# make empty df_combined
df_combined = pd.DataFrame(columns=columns)

# Menggabungkan df dan df_json menjadi df_combined dengan kolom 'content', 'title', 'content_tokens_stopwords_stemmed', 'title_tokens_stopwords_stemmed'
df_combined = pd.concat([df, df_json[columns]], ignore_index=True)
df_combined = df_combined.drop(df_combined.columns.difference(columns), axis=1)
df_combined

,title,content,title_tokens_stopwords_stemmed,content_tokens_stopwords_stemmed
0,"Ibu, Perhatikan 5 Hal Ini saat Memilih Car Se...","Bagi orang tua yang memiliki kendaraan, memili...","[, perhati, 5, pilih, car, seat, newborn]","[orang, tua, milik, kendara, , memilihcar, sea..."
1,"Catat, Ini 6 Tips Menyimpan Beras agar Tidak ...",Sebagai makanan pokok beras harus disimpan den...,"[catat, , 6, tips, simpan, beras, kutu]","[makan, pokok, beras, simpan, kualitas, turun,..."
2,"Waspada, Ini 6 Bahaya Asap Rokok bagi Kesehat...",Merokok tidak hanya berbahaya untuk dirimu sen...,"[waspada, , 6, bahaya, asap, rokok, sehat, anak]","[rokok, bahaya, diri, orang, sekitar, , bayi, ..."
3,"Sering Terkena Polusi, Ketahui Berbagi Cara B...","Sehari-hari, manusia terpapar polusi dalam jum...","[kena, polusi, , tahu, bagi, sih, paru]","[hari, , manusia, papar, polusi, asap, kendara..."
4,Ini Risiko dan Manfaat Implan Payudara yang P...,Implan payudara adalah prosedur bedah kosmetik...,"[risiko, manfaat, implan, payudara]","[implan, payudara, prosedur, bedah, kosmetik, ..."
...,...,...,...,...
24057,Filosofi inilah yang menjadi pegangan bagi ana...,JANGAN engkau terus meratapi nasib hanya karen...,"[filosofi, pegang, anak, delapan, puluh, sauda...","[engkau, ratap, nasib, takdir, lahir, keluarga..."
24058,"Jakarta , CNN Indonesia - - Aktris Lindsay L...",Aktris Lindsay Lohan mencuri perhatian publ...,"[jakarta, , cnn, indonesia, -, -, aktris, lind...","[aktris, lindsay, loh, curi, perhati, publik, ..."
24059,Jakarta ( ANTARA News ) - Doktor Biomedik dari...,Doktor Biomedik dari Fakultas Kedokteran Unive...,"[jakarta, , news, , -, doktor, biomedik, fakul...","[doktor, biomedik, fakultas, dokter, universit..."
24060,"Jakarta , CNN Indonesia - - Tim peneliti Indon...",Tim peneliti Indonesia yang bergabung dalam...,"[jakarta, , cnn, indonesia, -, -, tim, teliti,...","[tim, teliti, indonesia, gabung, murdoch, chil..."
24061,"Kalau Diop dijuluki ratu melanin , gadis asal ...",Kalau tahun lalu Khoudia Diop memukau seluruh ...,"[diop, juluk, ratu, melanin, , gadis, sudan, s...","[khoudia, diop, pukau, dunia, kulit, hitam, pe..."

In [13]:
# Drop null values
df_combined = df_combined.dropna()
df_combined = df_combined.reset_index(drop=True)
print(len(df_combined))

24060

In [14]:
# Tambahkan kolom 'document_id' pada df_combined
df_combined['document_id'] = df_combined.index
df_combined

,title,content,title_tokens_stopwords_stemmed,content_tokens_stopwords_stemmed,document_id
0,"Ibu, Perhatikan 5 Hal Ini saat Memilih Car Se...","Bagi orang tua yang memiliki kendaraan, memili...","[, perhati, 5, pilih, car, seat, newborn]","[orang, tua, milik, kendara, , memilihcar, sea...",0
1,"Catat, Ini 6 Tips Menyimpan Beras agar Tidak ...",Sebagai makanan pokok beras harus disimpan den...,"[catat, , 6, tips, simpan, beras, kutu]","[makan, pokok, beras, simpan, kualitas, turun,...",1
2,"Waspada, Ini 6 Bahaya Asap Rokok bagi Kesehat...",Merokok tidak hanya berbahaya untuk dirimu sen...,"[waspada, , 6, bahaya, asap, rokok, sehat, anak]","[rokok, bahaya, diri, orang, sekitar, , bayi, ...",2
3,"Sering Terkena Polusi, Ketahui Berbagi Cara B...","Sehari-hari, manusia terpapar polusi dalam jum...","[kena, polusi, , tahu, bagi, sih, paru]","[hari, , manusia, papar, polusi, asap, kendara...",3
4,Ini Risiko dan Manfaat Implan Payudara yang P...,Implan payudara adalah prosedur bedah kosmetik...,"[risiko, manfaat, implan, payudara]","[implan, payudara, prosedur, bedah, kosmetik, ...",4
...,...,...,...,...,...
24055,Filosofi inilah yang menjadi pegangan bagi ana...,JANGAN engkau terus meratapi nasib hanya karen...,"[filosofi, pegang, anak, delapan, puluh, sauda...","[engkau, ratap, nasib, takdir, lahir, keluarga...",24055
24056,"Jakarta , CNN Indonesia - - Aktris Lindsay L...",Aktris Lindsay Lohan mencuri perhatian publ...,"[jakarta, , cnn, indonesia, -, -, aktris, lind...","[aktris, lindsay, loh, curi, perhati, publik, ...",24056
24057,Jakarta ( ANTARA News ) - Doktor Biomedik dari...,Doktor Biomedik dari Fakultas Kedokteran Unive...,"[jakarta, , news, , -, doktor, biomedik, fakul...","[doktor, biomedik, fakultas, dokter, universit...",24057
24058,"Jakarta , CNN Indonesia - - Tim peneliti Indon...",Tim peneliti Indonesia yang bergabung dalam...,"[jakarta, , cnn, indonesia, -, -, tim, teliti,...","[tim, teliti, indonesia, gabung, murdoch, chil...",24058
24059,"Kalau Diop dijuluki ratu melanin , gadis asal ...",Kalau tahun lalu Khoudia Diop memukau seluruh ...,"[diop, juluk, ratu, melanin, , gadis, sudan, s...","[khoudia, diop, pukau, dunia, kulit, hitam, pe...",24059

In [15]:
# df_combined.to_csv('df_combined.csv', index=False)

In [16]:
df_combined['content_tokens_stopwords_stemmed'] = df_combined['content_tokens_stopwords_stemmed'].apply(lambda tokens: ' '.join(tokens))
df_combined['title_tokens_stopwords_stemmed'] = df_combined['title_tokens_stopwords_stemmed'].apply(lambda tokens: ' '.join(tokens))
df_combined.head()

,title,content,title_tokens_stopwords_stemmed,content_tokens_stopwords_stemmed,document_id
0,"Ibu, Perhatikan 5 Hal Ini saat Memilih Car Se...","Bagi orang tua yang memiliki kendaraan, memili...",perhati 5 pilih car seat newborn,orang tua milik kendara memilihcar seat newbo...,0
1,"Catat, Ini 6 Tips Menyimpan Beras agar Tidak ...",Sebagai makanan pokok beras harus disimpan den...,catat 6 tips simpan beras kutu,makan pokok beras simpan kualitas turun sayan...,1
2,"Waspada, Ini 6 Bahaya Asap Rokok bagi Kesehat...",Merokok tidak hanya berbahaya untuk dirimu sen...,waspada 6 bahaya asap rokok sehat anak,rokok bahaya diri orang sekitar bayi anak as...,2
3,"Sering Terkena Polusi, Ketahui Berbagi Cara B...","Sehari-hari, manusia terpapar polusi dalam jum...",kena polusi tahu bagi sih paru,hari manusia papar polusi asap kendara asap ...,3
4,Ini Risiko dan Manfaat Implan Payudara yang P...,Implan payudara adalah prosedur bedah kosmetik...,risiko manfaat implan payudara,implan payudara prosedur bedah kosmetik tempat...,4

In [17]:
df_combined.tail()

,title,content,title_tokens_stopwords_stemmed,content_tokens_stopwords_stemmed,document_id
24055,Filosofi inilah yang menjadi pegangan bagi ana...,JANGAN engkau terus meratapi nasib hanya karen...,filosofi pegang anak delapan puluh saudara la...,engkau ratap nasib takdir lahir keluarga yaki...,24055
24056,"Jakarta , CNN Indonesia - - Aktris Lindsay L...",Aktris Lindsay Lohan mencuri perhatian publ...,jakarta cnn indonesia - - aktris lindsay loh ...,aktris lindsay loh curi perhati publik tampil ...,24056
24057,Jakarta ( ANTARA News ) - Doktor Biomedik dari...,Doktor Biomedik dari Fakultas Kedokteran Unive...,jakarta news - doktor biomedik fakultas dokt...,doktor biomedik fakultas dokter universitas in...,24057
24058,"Jakarta , CNN Indonesia - - Tim peneliti Indon...",Tim peneliti Indonesia yang bergabung dalam...,jakarta cnn indonesia - - tim teliti indonesi...,tim teliti indonesia gabung murdoch children s...,24058
24059,"Kalau Diop dijuluki ratu melanin , gadis asal ...",Kalau tahun lalu Khoudia Diop memukau seluruh ...,diop juluk ratu melanin gadis sudan selatan k...,khoudia diop pukau dunia kulit hitam pekat gi...,24059

# Top 1

In [18]:
# Melakukan word embedding pada content_tokens_stopwords_stemmed (dokumen/konteks) menggunakan TF-IDF
X_combined = embedding.fit_transform(df_combined['content_tokens_stopwords_stemmed'])

# Melakukan fit/training pada NearestNeighbors
retriever.fit(X_combined)

NearestNeighbors(metric='cosine', n_neighbors=1)

In [19]:
# Melakukan word embedding pada title_tokens_stopwords_stemmed (query) menggunakan TF-IDF
X_ev_combined = embedding.transform(df_combined['title_tokens_stopwords_stemmed'])
X_ev_combined.shape

(24060, 119434)

In [20]:
# Melakukan prediksi dengan menggunakan NearestNeighbors
y_pred_combined = retriever.kneighbors(X_ev_combined, return_distance=False)
y_pred_combined.shape

(24060, 1)

In [21]:
# Menghitung akurasi
acc = top_accuracy(df_combined['document_id'], y_pred_combined)
print('Jumlah Benar\t:', int(acc*len(df_combined['document_id'])), 'dari', len(df_combined['document_id']))
print('Akurasi\t\t:', f'{acc:.4f}')

Jumlah Benar	: 19640 dari 24060
Akurasi		: 0.8163

## Example Use (Implementasi Penggunaan)

In [22]:
# example use get df_combined['content'] based on document_id
query = 'keadaan terbaik'

# Melakukan stemming pada query (question/pertanyaan yang dimasukkan) menggunakan Sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()
stop_words = set(stopwords.words('indonesian'))

# Menghilangkan stopwords dan melakukan stemming pada query 
query = [stemmer.stem(word) for word in word_tokenize(query) if word not in stop_words]
query = ' '.join(query)

X_ev = embedding.transform([query])
y_pred = retriever.kneighbors(X_ev, return_distance=False)
y_pred

array([[18268]], dtype=int64)

In [24]:
selected = df_combined.iloc[y_pred[0][0]]['content']
selected

' Jika industri perfilman punya ajang penghargaan Academy Awards , maka industri pariwisata juga punya ajang bergengsi yang dinamakan World Travel Awards ( WTA ) . Tahun ini , \xa0 WTA 2017 menobatkan sejumlah negara dan perusahaan yang bergerak di industri wisata sebagai yang terbaik dalam beberapa kategori . Galapagos di Ekuador memenangkan kategori Destinasi Pantai Terbaik , sementara Machu Picchu memenangkan kategori Objek Wisata Terbaik . Bandara Internasional Changi di Singapura memenangkan kategori Bandara Terbaik , yang diikuti dengan Singapore Airlines yang memenangkan kategori Maskapai Terbaik . Galapagos terpilih menjadi pemenang karena dianggap memiliki layanan dan fasilitas penunjang kenyamanan turis yang mumpuni . Ditambah lagi dengan pemandangan alamnya yang indah . Kepulauan ini masuk dalam daftar Situs Warisan Dunia UNESCO , karena memiliki 19 pulau yang menyimpan kekayaan bawah laut . Galapagos juga menjadi sumber inspirasi Charles Darwin yang menulis teori evolusi , saat ia berkunjung ke sana pada tahun 1835 . Untuk menuju ke sana , turis bisa menumpang pesawat dari Amerika Selatan . Musim panas di Galapagos berlangsung dari bulan Desember sampai Juni . Selebihnya , hujan akan turun dengan suhu yang lembab . Butuh merogoh kocek lebih dalam untuk berwisata di sini , karena pulau-pulau yang bisa dikunjungi berada cukup jauh dari keramaian . Sesampainya di sana , turis bisa menyewa sepeda , mobil , atau \xa0 helikopter untuk berkeliling . Yang paling seru ialah menjelajah perairannya dengan yacht . Ada banyak hal yang bisa dilakukan di Galapagos , mulai dari berenang , memancing , surfing , sampai menyelam . Bisa juga mengamati habitat hewan khas di sana , seperti penyu , penguin , sampai singa . Berikut ini ialah daftar lengkap pemenang WTA 2017 : Maskapai Terbaik : Singapore Airlines Bandara Terbaik : Changi Airport , Singapura Pantai Terbaik : Galapagos , Ekuador Hotel Butik Terbaik : Saxon Hotel , Villas and Spa , Afrika Selatan Resor Kasino Terbaik : Wynn Las Vegas , Nevada Kapal Pesiar Terbaik : Norwegian Cruise Line Hotel Desain Terbaik : Armani Hotel Dubai , Uni Emirat Arab Restoran Fine Dining Terbaik : La Maison 1888 , InterContinental Danang Pulau Terbaik : Madeira'

In [25]:
transform_text(embedding, selected)

Text:  Jika industri perfilman punya ajang penghargaan Academy Awards , maka industri pariwisata juga punya ajang bergengsi yang dinamakan World Travel Awards ( WTA ) . Tahun ini ,   WTA 2017 menobatkan sejumlah negara dan perusahaan yang bergerak di industri wisata sebagai yang terbaik dalam beberapa kategori . Galapagos di Ekuador memenangkan kategori Destinasi Pantai Terbaik , sementara Machu Picchu memenangkan kategori Objek Wisata Terbaik . Bandara Internasional Changi di Singapura memenangkan kategori Bandara Terbaik , yang diikuti dengan Singapore Airlines yang memenangkan kategori Maskapai Terbaik . Galapagos terpilih menjadi pemenang karena dianggap memiliki layanan dan fasilitas penunjang kenyamanan turis yang mumpuni . Ditambah lagi dengan pemandangan alamnya yang indah . Kepulauan ini masuk dalam daftar Situs Warisan Dunia UNESCO , karena memiliki 19 pulau yang menyimpan kekayaan bawah laut . Galapagos juga menjadi sumber inspirasi Charles Darwin yang menulis teori evolusi , saat ia berkunjung ke sana pada tahun 1835 . Untuk menuju ke sana , turis bisa menumpang pesawat dari Amerika Selatan . Musim panas di Galapagos berlangsung dari bulan Desember sampai Juni . Selebihnya , hujan akan turun dengan suhu yang lembab . Butuh merogoh kocek lebih dalam untuk berwisata di sini , karena pulau-pulau yang bisa dikunjungi berada cukup jauh dari keramaian . Sesampainya di sana , turis bisa menyewa sepeda , mobil , atau   helikopter untuk berkeliling . Yang paling seru ialah menjelajah perairannya dengan yacht . Ada banyak hal yang bisa dilakukan di Galapagos , mulai dari berenang , memancing , surfing , sampai menyelam . Bisa juga mengamati habitat hewan khas di sana , seperti penyu , penguin , sampai singa . Berikut ini ialah daftar lengkap pemenang WTA 2017 : Maskapai Terbaik : Singapore Airlines Bandara Terbaik : Changi Airport , Singapura Pantai Terbaik : Galapagos , Ekuador Hotel Butik Terbaik : Saxon Hotel , Villas and Spa , Afrika Selatan Resor Kasino Terbaik : Wynn Las Vegas , Nevada Kapal Pesiar Terbaik : Norwegian Cruise Line Hotel Desain Terbaik : Armani Hotel Dubai , Uni Emirat Arab Restoran Fine Dining Terbaik : La Maison 1888 , InterContinental Danang Pulau Terbaik : Madeira
Vect: [array(['yang', 'yacht', 'wynn', 'wta', 'world', 'wisata', 'villas',
       'vegas', 'untuk', 'uni', 'unesco', 'turun', 'turis', 'travel',
       'teori', 'tahun', 'surfing', 'sumber', 'suhu', 'spa', 'situs',
       'sini', 'singapura', 'singapore', 'singa', 'seru', 'seperti',
       'sepeda', 'sementara', 'selatan', 'saxon', 'sana', 'sampai',
       'saat', 'restoran', 'resor', 'punya', 'pulau', 'picchu', 'pesiar',
       'pesawat', 'penyu', 'penguin', 'pariwisata', 'pantai', 'panas',
       'paling', 'pada', 'objek', 'norwegian', 'nevada', 'negara',
       'musim', 'mumpuni', 'mulai', 'mobil', 'menjadi', 'masuk',
       'maskapai', 'maka', 'maison', 'madeira', 'machu', 'line',
       'lengkap', 'lembab', 'lebih', 'laut', 'las', 'lagi', 'la', 'kocek',
       'khas', 'ke', 'kategori', 'kasino', 'karena', 'kapal', 'juni',
       'juga', 'jika', 'jauh', 'internasional', 'intercontinental',
       'inspirasi', 'ini', 'industri', 'indah', 'ia', 'hujan', 'hotel',
       'hewan', 'helikopter', 'hal', 'habitat', 'galapagos', 'fine',
       'fasilitas', 'evolusi', 'emirat', 'ekuador', 'dunia', 'dubai',
       'di', 'destinasi', 'desember', 'desain', 'dengan', 'darwin',
       'dari', 'danang', 'dan', 'dalam', 'daftar', 'cukup', 'cruise',
       'charles', 'changi', 'butuh', 'butik', 'bulan', 'bisa', 'beberapa',
       'bawah', 'banyak', 'bandara', 'awards', 'atau', 'armani', 'arab',
       'and', 'amerika', 'akan', 'ajang', 'airport', 'airlines', 'afrika',
       'ada', 'academy', '2017', '19', '1888', '1835'], dtype='<U72')]

# Top 3

In [26]:
retriever_3.fit(X_combined)

NearestNeighbors(metric='cosine', n_neighbors=3)

In [27]:
y_pred_combined_3 = retriever_3.kneighbors(X_ev_combined, return_distance=False)
acc_3 = top_accuracy(df_combined['document_id'], y_pred_combined_3)
print('Jumlah Benar\t:', int(acc_3*len(df_combined['document_id'])), 'dari', len(df_combined['document_id']))
print('Akurasi\t\t:', f'{acc_3:.4f}')

Jumlah Benar	: 22121 dari 24060
Akurasi		: 0.9194

# Top 9

In [28]:
retriever_9.fit(X_combined)

NearestNeighbors(metric='cosine', n_neighbors=9)

In [29]:
y_pred_combined_9 = retriever_9.kneighbors(X_ev_combined, return_distance=False)
acc_9 = top_accuracy(df_combined['document_id'], y_pred_combined_9)
print('Jumlah Benar\t:', int(acc_9*len(df_combined['document_id'])), 'dari', len(df_combined['document_id']))
print('Akurasi\t\t:', f'{acc_9:.4f}')

Jumlah Benar	: 23417 dari 24060
Akurasi		: 0.9733

In [46]:
import pickle

# save embedding and retriever
pickle.dump(embedding, open('embedding.pkl', 'wb'))
pickle.dump(retriever_9, open('retriever.pkl', 'wb'))

# Evaluation (Top 1-3-9)

In [30]:
# Berikut adalah dataframe evaluasi untuk semua konfigurasi NN (accuracy)
#  - Top 1 
#  - Top 3
#  - Top 9

df_acc = pd.DataFrame(columns=['k=1', 'k=3', 'k=9'])
df_acc.loc['Accuracy'] = [acc, acc_3, acc_9]
df_acc

               k=1      k=3       k=9
Accuracy  0.816293  0.91941  0.973275

# With new dataset

In [31]:
df_combined_new_query = pd.read_csv('df_combined_new_query.csv')

In [32]:
df_combined_new_query['new_query']

0                                                NaN
1                                                NaN
2        bagaimana asap rokok mempengaruhi anak-anak
3                                                NaN
4                       apa manfaat implan payudara?
                            ...
24055                               siapa akp wawan?
24056                                            NaN
24057                                            NaN
24058                                            NaN
24059                                            NaN
Name: new_query, Length: 24060, dtype: object

In [33]:
df_combined_new_query['new_query'][2]

'bagaimana asap rokok mempengaruhi anak-anak'

In [34]:
import nltk
df_combined_new_query['new_query'] = df_combined_new_query['new_query'].str.lower()


# nltk.download('punkt')
df_combined_new_query['new_query_tokens'] = df_combined_new_query['new_query'].apply(lambda query: nltk.word_tokenize(query) if pd.notnull(query) else [])

# nltk.download('stopwords')
# stop_words = set(stopwords.words('indonesian'))
df_combined_new_query['new_query_tokens_stopwords'] = df_combined_new_query['new_query_tokens'].apply(lambda x: [word for word in x if word not in stop_words])

# factory = StemmerFactory()
# stemmer = factory.create_stemmer()
df_combined_new_query['new_query_tokens_stopwords_stemmed'] = df_combined_new_query['new_query_tokens_stopwords'].apply(lambda x: [stemmer.stem(word) for word in x])
df_combined_new_query.head()

,title,content,title_tokens_stopwords_stemmed,content_tokens_stopwords_stemmed,document_id,new_query,new_query_tokens,new_query_tokens_stopwords,new_query_tokens_stopwords_stemmed
0,"Ibu, Perhatikan 5 Hal Ini saat Memilih Car Se...","Bagi orang tua yang memiliki kendaraan, memili...","['', 'perhati', '5', 'pilih', 'car', 'seat', '...","['orang', 'tua', 'milik', 'kendara', '', 'memi...",0,NaN,[],[],[]
1,"Catat, Ini 6 Tips Menyimpan Beras agar Tidak ...",Sebagai makanan pokok beras harus disimpan den...,"['catat', '', '6', 'tips', 'simpan', 'beras', ...","['makan', 'pokok', 'beras', 'simpan', 'kualita...",1,NaN,[],[],[]
2,"Waspada, Ini 6 Bahaya Asap Rokok bagi Kesehat...",Merokok tidak hanya berbahaya untuk dirimu sen...,"['waspada', '', '6', 'bahaya', 'asap', 'rokok'...","['rokok', 'bahaya', 'diri', 'orang', 'sekitar'...",2,bagaimana asap rokok mempengaruhi anak-anak,"[bagaimana, asap, rokok, mempengaruhi, anak-anak]","[asap, rokok, mempengaruhi, anak-anak]","[asap, rokok, pengaruh, anak]"
3,"Sering Terkena Polusi, Ketahui Berbagi Cara B...","Sehari-hari, manusia terpapar polusi dalam jum...","['kena', 'polusi', '', 'tahu', 'bagi', 'sih', ...","['hari', '', 'manusia', 'papar', 'polusi', 'as...",3,NaN,[],[],[]
4,Ini Risiko dan Manfaat Implan Payudara yang P...,Implan payudara adalah prosedur bedah kosmetik...,"['risiko', 'manfaat', 'implan', 'payudara']","['implan', 'payudara', 'prosedur', 'bedah', 'k...",4,apa manfaat implan payudara?,"[apa, manfaat, implan, payudara, ?]","[manfaat, implan, payudara, ?]","[manfaat, implan, payudara, ]"

In [35]:
df_combined_new_query.new_query_tokens_stopwords_stemmed[2][3]

'anak'

In [36]:
# df_combined_new_query['new_query_tokens_stopwords_stemmed'] = df_combined_new_query['new_query_tokens_stopwords_stemmed'].apply(ast.literal_eval)
additional_queries = df_combined_new_query['new_query_tokens_stopwords_stemmed'].apply(lambda tokens: ' '.join(tokens) if len(tokens) != 0 else '')
additional_queries = pd.DataFrame({'query': additional_queries, 'document_id': df_combined_new_query['document_id']})
additional_queries.head()

                      query  document_id
0                                      0
1                                      1
2  asap rokok pengaruh anak            2
3                                      3
4  manfaat implan payudara             4

In [37]:
# drop null values (70% of the data)
# Menghapus baris yang memiliki array kosong pada kolom "query"
empty_query_rows = additional_queries[additional_queries['query'].apply(lambda x: len(x) == 0)]
additional_queries = additional_queries.drop(empty_query_rows.index)
additional_queries = additional_queries.reset_index(drop=True)
print(additional_queries.shape)
additional_queries.head()

(7217, 2)

                      query  document_id
0  asap rokok pengaruh anak            2
1  manfaat implan payudara             4
2                tes urine             6
3    jaga sehat mental anak           10
4    tutup bekas cium leher           11

In [38]:
X_ev_doc2query = embedding.transform(additional_queries['query'])
y_ev_doc2query = additional_queries['document_id']
y_pred_doc2query = retriever.kneighbors(X_ev_doc2query, return_distance=False)
print(y_pred_doc2query.shape)

(7217, 1)

## Top 1

In [39]:
acc = top_accuracy(y_ev_doc2query, y_pred_doc2query)
print('Jumlah Benar\t:', int(acc*len(y_ev_doc2query)), 'dari', len(y_ev_doc2query))
print('Akurasi\t\t:', f'{acc:.4f}')

Jumlah Benar	: 3076 dari 7217
Akurasi		: 0.4262

## Top 3

In [40]:
# untuk retriever_3
y_pred_doc2query_3 = retriever_3.kneighbors(X_ev_doc2query, return_distance=False)
acc_3 = top_accuracy(y_ev_doc2query, y_pred_doc2query_3)
print('Jumlah Benar\t:', int(acc_3*len(y_ev_doc2query)), 'dari', len(y_ev_doc2query))
print('Akurasi\t\t:', f'{acc_3:.4f}')

Jumlah Benar	: 4580 dari 7217
Akurasi		: 0.6346

## Top 9

In [41]:
# untuk retriever_10
y_pred_doc2query_9 = retriever_9.kneighbors(X_ev_doc2query, return_distance=False)
acc_9 = top_accuracy(y_ev_doc2query, y_pred_doc2query_9)
print('Jumlah Benar\t:', int(acc_9*len(y_ev_doc2query)), 'dari', len(y_ev_doc2query))
print('Akurasi\t\t:', f'{acc_9:.4f}')

Jumlah Benar	: 5689 dari 7217
Akurasi		: 0.7883